// Generated by scripts/gen-stars.mjs — do not edit by hand.
// Seed for the top bar's star count; the browser refreshes it. Regenerate with
// `pnpm stars` (`pnpm build` does it for you).

export const githubStars = 8167;
