import type { CopyTable } from './types';

export const zh: CopyTable = {
  'nav.docs': '文档',
  'nav.blog': '博客',
  'nav.download': '下载',
  'nav.community': '社区',
  'nav.community.github': 'GitHub',
  'nav.community.githubBody': '源码、Issues 与 Releases。',
  'nav.community.discord': 'Discord',
  'nav.community.discordBody': '提问，跟进开发进展。',
  'nav.community.qq': 'QQ 群',
  'nav.community.qqBody': '中文交流群。',
  'nav.stars': '个 GitHub 星标',
  'nav.menu': '打开菜单',

  'hero.title': '下载器的集大成者。',
  'hero.subtitle':
    '一个能嗅探网页媒体、录制直播流、取代五个工具的下载器。够快，免费，开源。',
  'hero.ctaPrimary': '免费下载',
  'hero.cta.windows': '下载 Windows 版',
  'hero.cta.macos': '下载 macOS 版',
  'hero.cta.linux': '下载 Linux 版',
  'hero.cta.android': '下载 Android 版',
  'hero.ctaSecondary': '查看文档',
  'hero.shotAlt': 'Ghost Downloader 同时运行多个下载任务',

  'resilience.title': '快在刀刃上。',
  'resilience.body':
    '好网谁都快。限速、拥堵、半残——别人卡住的地方，我们拉开差距。',
  'resilience.stat1.value': '2.5×',
  'resilience.stat1.label': '弱网环境下的速度提升',
  'resilience.stat2.value': '100%',
  'resilience.stat2.label': '测试下载全部完成',
  'resilience.stat3.value': '0',
  'resilience.stat3.label': '被反爬拦截的下载数',
  'resilience.note':
    '六项真实下载测试，连接数对等。Ghost Downloader 全部完成，五项最快。',
  'resilience.noteLink': '查看完整对比测试',

  'sniff.title': '所见即所得。',
  'sniff.body':
    '扩展替你盯着页面，找出播放器背后的流媒体，交给桌面端，然后退场。',
  'sniff.beat1.title': '按钮就在你看的地方',
  'sniff.beat1.body':
    '下载按钮直接出现在视频上。无画质上限，不封顶在 720p。',
  'sniff.beat1.alt': '视频页面上显示的下载按钮',
  'sniff.beat2.title': '页面资源一目了然',
  'sniff.beat2.body':
    '视频、音频、图片、HLS 和 DASH 流——打开弹窗，按需取用。',
  'sniff.beat2.alt': '扩展弹窗列出嗅探到的媒体资源',
  'sniff.beat3.title': '直达桌面应用',
  'sniff.beat3.body':
    '无需在窗口间复制链接。扩展负责侦察，桌面引擎负责下载。',
  'sniff.beat3.alt': '嗅探到的任务出现在桌面应用中',

  'protocols.title': '合，而不同。',
  'protocols.body':
    '大多数人最终要装下载器、种子客户端、直播录制工具、视频解析器，外加命令行工具。Ghost Downloader 一个全包。',
  'protocols.http.name': 'HTTP',
  'protocols.http.note': '智能分块，无需合并',
  'protocols.torrent.name': 'BitTorrent',
  'protocols.torrent.note': '磁力链接与种子文件',
  'protocols.ftp.name': 'FTP',
  'protocols.ftp.note': '明文与 TLS 加密',
  'protocols.m3u8.name': 'M3U8',
  'protocols.m3u8.note': '点播与直播',
  'protocols.dash.name': 'MPEG-DASH',
  'protocols.dash.note': '自适应流媒体',
  'protocols.ed2k.name': 'eD2k',
  'protocols.ed2k.note': '经典电驴网络',
  'protocols.live.title': '直播实时录制',
  'protocols.live.body':
    'M3U8 流媒体实时解密录制——桌面端和安卓端均支持。',
  'protocols.live.alt': 'Ghost Downloader 正在录制 M3U8 直播流',
  'protocols.parsers.title': '专属解析引擎',
  'protocols.parsers.body':
    'YouTube 和哔哩哔哩最高支持 4K HDR，含字幕和播放列表。GitHub Release 和 HuggingFace 模型支持镜像加速。',
  'protocols.parsers.alt': '画质选择对话框，显示 4K 和 HDR 选项',

  'protocols.android.title': '换壳不换芯。',
  'protocols.android.body':
    '直播录制，后台下载。桌面能做的，这里都能。',
  'protocols.android.alt1': 'Ghost Downloader 在安卓上录制直播',
  'protocols.android.alt2': 'Ghost Downloader 安卓端下载列表',
  'protocols.android.alt3': 'Ghost Downloader 安卓端完成通知',

  'download.windows.subtitle': 'Exe / Zip · x64 · arm64',
  'download.macos.subtitle': 'Apple Silicon / Intel · macOS 13+',
  'download.linux.subtitle': 'AppImage / Deb / Tar.xz · x64 · arm64',
  'download.android.subtitle': 'APK · Android 10+',
  'download.title.prefix': '下载',
  'download.title.brand': 'Ghost Downloader',
  'download.subtitle': '五合一。免费，开源。',
  'download.unavailable': '正在加载发布资源——请前往 GitHub Releases 页面。',
  'download.viewReleases': '查看所有版本',
  'download.installer': '安装版',
  'download.portable': '便携版',
  'download.appImage': 'AppImage',
  'download.deb': 'Deb 包',
  'download.tarXz': 'Tar 压缩包',
  'download.appleSilicon': 'Apple Silicon',
  'download.intel': 'Intel',
  'download.x64': 'x64',
  'download.arm64': 'arm64',
  'download.recommended': '推荐',
  'download.app.title': '客户端',
  'download.extension.title': '浏览器扩展',
  'download.chrome.subtitle': 'Chrome 应用商店',
  'download.edge.subtitle': 'Edge 外接程序',
  'download.firefox.subtitle': 'Firefox 附加组件',

  'footer.copyright': '© 2026 晓游. All Rights Reserved.',
  'footer.icp': '湘ICP备2026012876号-1',
  'footer.publicSecurity': '湘公网安备43072402000246号',
  'footer.docs': '文档',
  'footer.github': 'GitHub',
  'footer.discord': 'Discord',
  'footer.qq': 'QQ 群',
  'footer.donate': '捐赠',
};
