/**
 * Freezes the handful of Material Design Icons we use into a plain TypeScript
 * module.
 *
 * Why this exists: `@iconify-json/mdi` ships all 7638 icons as a single JSON
 * module. A bundler can only keep or drop a JSON module whole — it cannot
 * tree-shake individual keys — so importing it from any component that ends up
 * on the client shipped a 3.0 MB chunk (756 KB gzip) to render seven icons.
 *
 * The generated file is committed, so a normal install and build never need the
 * icon pack at all; it stays a devDependency for regeneration only.
 *
 * Run with `pnpm icons` after changing ICONS below.
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const require = createRequire(import.meta.url);
const pack = require('@iconify-json/mdi/icons.json');
const { version } = require('@iconify-json/mdi/package.json');

/** Our name → the name inside the mdi pack. */
const ICONS = {
  windows: 'microsoft-windows',
  apple: 'apple',
  linux: 'linux',
  android: 'android',
  chrome: 'google-chrome',
  edge: 'microsoft-edge',
  firefox: 'firefox',
};

/** Brand icons maintained manually (Simple Icons, CC0-1.0). MDI's versions are outdated. */
const MANUAL_ICONS = {
  discord: 'M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z',
  qq: 'M21.395 15.035a40 40 0 0 0-.803-2.264l-1.079-2.695c.001-.032.014-.562.014-.836C19.526 4.632 17.351 0 12 0S4.474 4.632 4.474 9.241c0 .274.013.804.014.836l-1.08 2.695a39 39 0 0 0-.802 2.264c-1.021 3.283-.69 4.643-.438 4.673.54.065 2.103-2.472 2.103-2.472 0 1.469.756 3.387 2.394 4.771-.612.188-1.363.479-1.845.835-.434.32-.379.646-.301.778.343.578 5.883.369 7.482.189 1.6.18 7.14.389 7.483-.189.078-.132.132-.458-.301-.778-.483-.356-1.233-.646-1.846-.836 1.637-1.384 2.393-3.302 2.393-4.771 0 0 1.563 2.537 2.103 2.472.251-.03.581-1.39-.438-4.673',
};

const entries = Object.entries(ICONS).map(([key, source]) => {
  const icon = pack.icons[source];
  if (!icon) throw new Error(`mdi has no icon named "${source}"`);

  // We render a bare <path d> inside our own <svg fill="currentColor">, so the
  // extraction is only lossless while the body is exactly one path carrying
  // nothing but `fill="currentColor"`. Fail loudly rather than silently drop
  // an opacity, a transform or a second subpath if upstream redraws an icon.
  const stripped = icon.body.replace(/ d="[^"]*"/, ' d=""');
  if (stripped !== '<path fill="currentColor" d=""/>') {
    throw new Error(
      `mdi "${source}" is no longer a single plain path — extracting d= would ` +
        `lose information. Body: ${icon.body.slice(0, 200)}`,
    );
  }

  const width = icon.width ?? pack.width ?? 24;
  const height = icon.height ?? pack.height ?? 24;
  if (width !== 24 || height !== 24) {
    throw new Error(`mdi "${source}" is ${width}x${height}, not the 24x24 our viewBox assumes`);
  }

  return [key, icon.body.match(/ d="([^"]*)"/)[1]];
});

const manualEntries = Object.entries(MANUAL_ICONS);

const file = `// Generated by scripts/gen-icons.mjs — do not edit by hand.
// Platform/browser icons: @iconify-json/mdi@${version} (Material Design Icons, Apache-2.0).
// discord, qq: Simple Icons (CC0-1.0) — manually maintained for up-to-date brand marks.
// Run \`pnpm icons\` to regenerate.

export const mdiIcons = {
${entries.map(([key, d]) => `  ${key}: '${d}',`).join('\n')}
${manualEntries.map(([key, d]) => `  ${key}: '${d}',`).join('\n')}
} as const;

export type MdiIconName = keyof typeof mdiIcons;
`;

const out = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'lib',
  'icons.generated.ts',
);
writeFileSync(out, file);
console.log(`Wrote ${entries.length + manualEntries.length} icons (${entries.length} MDI + ${manualEntries.length} manual) to ${path.relative(process.cwd(), out)}`);
