/**
 * Bakes the repository's star count into a plain TypeScript module.
 *
 * Why this exists: `output: 'export'` means there is no server to ask at
 * request time, so a live count has to come from the browser. Fetching it
 * *only* in the browser leaves the bar rendering a blank or a skeleton on
 * every first paint. This seeds the number at build time; `<GithubStars />`
 * then refreshes it from api.github.com once the page is interactive, so the
 * count is live for anyone who waits a beat and merely stale-by-one-deploy for
 * anyone who does not.
 *
 * A failed fetch keeps whatever is already in the generated file rather than
 * breaking the build — an offline CI runner should still ship a number.
 *
 * Runs automatically before `pnpm build`, or on demand with `pnpm stars`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const out = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'lib',
  'stars.generated.ts',
);

const repo = 'XiaoYouChR/Ghost-Downloader-3';

function previousCount() {
  try {
    const match = readFileSync(out, 'utf8').match(/githubStars = (\d+)/);
    return match ? Number(match[1]) : null;
  } catch {
    return null;
  }
}

async function fetchCount() {
  const response = await fetch(`https://api.github.com/repos/${repo}`, {
    headers: {
      accept: 'application/vnd.github+json',
      'user-agent': 'ghost-downloader-website-build',
    },
  });
  if (!response.ok) {
    throw new Error(`GitHub API returned ${response.status}`);
  }
  const { stargazers_count: count } = await response.json();
  if (typeof count !== 'number') {
    throw new Error('GitHub API response had no stargazers_count');
  }
  return count;
}

let count;
try {
  count = await fetchCount();
  console.log(`Baked ${count} stars for ${repo}`);
} catch (error) {
  count = previousCount();
  if (count === null) {
    throw new Error(
      `Could not reach the GitHub API and ${path.relative(process.cwd(), out)} ` +
        `has no previous value to fall back on: ${error.message}`,
    );
  }
  console.warn(`GitHub API unreachable (${error.message}); keeping ${count}`);
}

writeFileSync(
  out,
  `// Generated by scripts/gen-stars.mjs — do not edit by hand.
// Seed for the top bar's star count; the browser refreshes it. Regenerate with
// \`pnpm stars\` (\`pnpm build\` does it for you).

export const githubStars = ${count};
`,
);
